apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  name: repo-gitops
  namespace: argocd
type: Opaque
stringData:
  username: jporeilly
  password: Pentaho2020# ## INSERT TOKEN HERE
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: cicd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/jporeilly/tekton-argocd-poc
      passwordSecret:
        name: repo-gitops
        key: password
      usernameSecret:
        name: repo-gitops
        key: username